version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:21
    working_directory: ~/repo

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: "Set up Maven"
          command: |
            mvn clean install
      - run:
          name: "Run Tests"
          command: |
            mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
